# -*- coding: utf-8 -*-
"""
Django settings for fablab-webif project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9wr6l)$t2q1mj289=)&$q8i@zf2#$9xy%=&ss_jyf8ngk9psoi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Enabled Dev environment switches the db from MySQL-Server to local SQlite DB
DEV = False

if DEV is True:
    TEMPLATE_DEBUG = True

# WARNING add allowed hosts
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s|%(asctime)s|%(module)s|%(process)d|%(thread)d|%(message)s',
            'datefmt' : "%Y-%b-%d %H:%M:%S"
        },
        'simple': {
            'format': '%(asctime)s - %(levelname)s - %(module)s | %(message)s',
            'datefmt': "%H:%M:%S"
        },
    },
    'loggers': {
        'fablab-webif': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
            }
    }
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fablabcontrol.apps.FabLabControl',
    'channels',
    'django_extensions',
    'bootstrap_ui',
    'widget_tweaks',
#    'template_debug',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fablab-webif.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'fablab-webif.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
if DEV is True:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
# WARNING add password
    db_password = u""

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            # WARNING add name and user
            'NAME': '',
            'USER': '',
            'PASSWORD': db_password,
            'HOST': '',
            'OPTIONS': {'ssl': {'ca': '/etc/ssl/lets-encrypt-x3-cross-signed.pem'}},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "fablab-webif.routing.channel_routing",
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = False

USE_TZ = True


DATETIME_INPUT_FORMATS = [
    '%d.%m.%Y %H:%M',        # '01.12.2001 14:30'
    '%m/%d/%Y %H:%M %p',        # '01.12.2001 14:30 AM'
    '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M:%S.%f',  # '2006-10-25 14:30:59.000200'
    '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
    '%Y-%m-%d',              # '2006-10-25'
    '%m/%d/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
    '%m/%d/%Y %H:%M:%S.%f',  # '10/25/2006 14:30:59.000200'
    '%m/%d/%Y %H:%M',        # '10/25/2006 14:30'
    '%m/%d/%Y',              # '10/25/2006'
    '%m/%d/%y %H:%M:%S',     # '10/25/06 14:30:59'
    '%m/%d/%y %H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
    '%m/%d/%y %H:%M',        # '10/25/06 14:30'
    '%m/%d/%y',              # '10/25/06'
]


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# user upload files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# mail settings
EMAIL_USE_TLS = False
# WARNING add Mail Host
EMAIL_HOST = ''
EMAIL_PORT = 25
#EMAIL_HOST_USER = 'me@gmail.com'
#EMAIL_HOST_PASSWORD = 'password'

# django-bootstrap-ui settings
DJANGO_BOOTSTRAP_UI_THEME = 'bootswatch-darkly'

# Possible bootstrap themes
# cerulean
# darkly
# flatly
# litera
# lumen
# minty
# sandstone
# slate
