# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabLabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uuid', models.CharField(max_length=14, unique=True, verbose_name='RFID UUID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Machine name')),
                ('circle_mac', models.CharField(max_length=16, unique=True, verbose_name='Plugwise Circle MAC')),
                ('circle_status', models.CharField(blank=True, max_length=16, verbose_name='Circle status')),
                ('esp_mac', models.CharField(max_length=12, unique=True, verbose_name='ESP Controller MAC')),
                ('esp_status', models.CharField(blank=True, max_length=16, verbose_name='ESP status')),
                ('users', models.ManyToManyField(blank=True, to='fablabcontrol.FabLabUser')),
            ],
        ),
    ]
