# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('power', models.DecimalField(decimal_places=6, max_digits=12)),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='always_on',
            field=models.BooleanField(default=False, verbose_name='Always on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='machine',
            name='loginterval',
            field=models.IntegerField(blank=True, default=15, verbose_name='Log interval in min.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='monitor',
            field=models.BooleanField(default=True, verbose_name='Monitor (10s)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='users',
            field=models.ManyToManyField(blank=True, to='fablabcontrol.FabLabUser', verbose_name='Assigned users'),
        ),
        migrations.AddField(
            model_name='energy',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fablabcontrol.Machine'),
        ),
    ]
