# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0002_auto_20171110_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='monitor',
            field=models.BooleanField(default=True, verbose_name='Monitor (10s)'),
        ),
    ]
