# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0003_auto_20171123_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateTimeField(verbose_name='Work begin')),
                ('datestop', models.DateTimeField(verbose_name='Work end')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fablabcontrol.Machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fablabcontrol.FabLabUser')),
            ],
        ),
    ]
