# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0004_usagemonitor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Energy',
            new_name='EnergyMonitor',
        ),
    ]
