# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0006_auto_20171123_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymonitor',
            name='interval',
            field=models.IntegerField(verbose_name='Log interval in min.'),
        ),
        migrations.AlterField(
            model_name='energymonitor',
            name='power',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Consumed energy in kW/h'),
        ),
        migrations.AlterField(
            model_name='usagemonitor',
            name='datestop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Work end'),
        ),
        migrations.AlterField(
            model_name='usagemonitor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
