# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0009_auto_20171128_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='fablabuser',
            name='image',
            field=models.ImageField(default='user_images/no-img.jpg', upload_to='user_images/', verbose_name='Image'),
        ),
    ]
