# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fablabcontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0010_fablabuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Briefing')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='BriefingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='briefings/')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fablabcontrol.Briefing')),
            ],
        ),
        migrations.AlterField(
            model_name='energymonitor',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy', to='fablabcontrol.Machine'),
        ),
        migrations.AlterField(
            model_name='fablabuser',
            name='image',
            field=models.ImageField(default='user_images/no-img.jpg', upload_to=fablabcontrol.models.get_path_and_name_for_picture, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='useractivitymonitor',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fablabcontrol.Machine'),
        ),
        migrations.AlterField(
            model_name='useractivitymonitor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fablabcontrol.FabLabUser'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='briefings',
            field=models.ManyToManyField(blank=True, to='fablabcontrol.Briefing', verbose_name='Briefings'),
        ),
    ]
