# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fablabcontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0012_auto_20171130_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fablabcontrol.models.get_path_and_name_for_activity_doc)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fablabcontrol.UserActivityMonitor')),
            ],
        ),
        migrations.AlterField(
            model_name='fablabuser',
            name='briefings',
            field=models.ManyToManyField(blank=True, related_name='users', to='fablabcontrol.Briefing', verbose_name='Briefings'),
        ),
    ]
