# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fablabcontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0013_auto_20171201_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField(verbose_name='Scheduled for')),
                ('duration', models.TimeField(verbose_name='Planned duration')),
                ('start', models.DateTimeField(verbose_name='Work begin')),
                ('stop', models.DateTimeField(blank=True, null=True, verbose_name='Work end')),
                ('todo', models.CharField(blank=True, max_length=300, null=True, verbose_name='ToDo')),
                ('done', models.TextField(blank=True, null=True, verbose_name='Done')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fablabcontrol.Machine')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fablabcontrol.FabLabUser')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fablabcontrol.models.get_path_and_name_for_maintenance_doc)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fablabcontrol.Maintenance')),
            ],
        ),
    ]
