# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fablabcontrol', '0014_maintenance_maintenancedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, unique=True, verbose_name='ESP MAC')),
            ],
        ),
        migrations.CreateModel(
            name='PlugwiseCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=16, unique=True, verbose_name='Plugwise Circle MAC')),
                ('status', models.CharField(blank=True, max_length=16, verbose_name='Circle status')),
                ('loginterval', models.IntegerField(blank=True, verbose_name='Log interval in min.')),
                ('always_on', models.BooleanField(verbose_name='Always on')),
                ('monitor', models.BooleanField(default=True, verbose_name='Monitor (10s)')),
                ('production', models.BooleanField(default=False, verbose_name='Energy producer')),
                ('schedule_state', models.CharField(default='off', max_length=3, verbose_name='Schedule state')),
                ('schedule', models.CharField(default='', max_length=16, verbose_name='Schedule')),
                ('savelog', models.BooleanField(default=True, verbose_name='Save energy log')),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='always_on',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='circle_mac',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='circle_status',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='esp_mac',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='esp_status',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='loginterval',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='monitor',
        ),
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_in', to='fablabcontrol.FabLabUser', verbose_name='Current user'),
        ),
        migrations.AlterField(
            model_name='energymonitor',
            name='power',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Consumed energy in W/h'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Planned duration'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled for'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Work begin'),
        ),
        migrations.AddField(
            model_name='plugwisecircle',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to='fablabcontrol.Machine'),
        ),
        migrations.AddField(
            model_name='esp',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esps', to='fablabcontrol.Machine'),
        ),
        migrations.AddField(
            model_name='energymonitor',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy', to='fablabcontrol.PlugwiseCircle'),
        ),
    ]
