from django.conf.urls import url

from . import views

app_name = 'fablabcontrol'
urlpatterns = [
    url(r'^$', views.machines, name='index'),
    url(r'^log_in/$', views.log_in, name='log_in'),
    url(r'^log_out/$', views.log_out, name='log_out'),
    url(r'^circle/$', views.circles, name='circles'),
    url(r'^circle/(?P<circle_id>[0-9]+)/$', views.circle, name='circle'),
    url(r'^circle/mod/(?P<circle_id>[0-9]+)/$', views.mod_circle, name='mod_circle'),
    url(r'^circle/energy/(?P<circle_id>[0-9]+)/$',
        views.circle_energy, name='circle_energy'),
    url(r'^circle/new/$', views.new_circle, name='new_circle'),
    url(r'^esp/$', views.esps, name='esps'),
    url(r'^esp/(?P<esp_id>[0-9]+)/$', views.esp, name='esp'),
    url(r'^esp/mod/(?P<esp_id>[0-9]+)/$', views.mod_esp, name='mod_esp'),
    url(r'^esp/new/$', views.new_esp, name='new_esp'),
    url(r'^machine/$', views.machines, name='machines'),
    url(r'^machine/(?P<machine_id>[0-9]+)/$', views.machine, name='machine'),
    url(r'^machine/mod/(?P<machine_id>[0-9]+)/$', views.mod_machine, name='mod_machine'),
    url(r'^machine/new/$', views.new_machine, name='new_machine'),
    url(r'^machine/activity/(?P<machine_id>[0-9]+)/$',
        views.machine_activity, name='machine_activity'),
    url(r'^machine/maintenance/(?P<machine_id>[0-9]+)/$',
        views.machine_maintenance, name='machine_maintenance'),
    url(r'^machine/energy/(?P<machine_id>[0-9]+)/$',
        views.machine_energy, name='machine_energy'),
    url(r'^machine/energy/$', views.machines_energy, name='machines_energy'),
    url(r'^user/$', views.users, name='users'),
    url(r'^user/(?P<fablabuser_id>[0-9]+)/$', views.user, name='user'),
    url(r'^user/mod/(?P<fablabuser_id>[0-9]+)/$', views.mod_user, name='mod_user'),
    url(r'^user/new/$', views.new_user, name='new_user'),
    url(r'^user/activity/(?P<fablabuser_id>[0-9]+)/$',
        views.user_activity, name='user_activity'),
    url(r'^user/maintenance/(?P<fablabuser_id>[0-9]+)/$',
        views.user_maintenance, name='user_maintenance'),
    url(r'^check/$', views.check_plugwise_config, name='check_pluwise_config'),
    url(r'^activity/$', views.activities, name='activities'),
    url(r'^activity/(?P<activity_id>[0-9]+)/$', views.activity, name='activity'),
    url(r'^activity/mod/(?P<activity_id>[0-9]+)/$',
        views.mod_activity, name='mod_activity'),
    url(r'^activity/new/$', views.new_activity, name='new_activity'),
    url(r'^briefing/$', views.briefings, name='briefings'),
    url(r'^briefing/(?P<briefing_id>[0-9]+)/$', views.briefing, name='briefing'),
    url(r'^briefing/mod/(?P<briefing_id>[0-9]+)/$',
        views.mod_briefing, name='mod_briefing'),
    url(r'^briefing/new/$', views.new_briefing, name='new_briefing'),
    url(r'^maintenance/$', views.maintenances, name='maintenances'),
    url(r'^maintenance/(?P<maintenance_id>[0-9]+)/$',
        views.maintenance, name='maintenance'),
    url(r'^maintenance/mod/(?P<maintenance_id>[0-9]+)/$',
        views.mod_maintenance, name='mod_maintenance'),
    url(r'^maintenance/new/$', views.new_maintenance, name='new_maintenance'),

]
